import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'pt-BR' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  'en': {
    'hero.title': 'Strategic Market Entry & Business Development for Healthcare and Life Sciences in Brazil and Latin America',
    'hero.subtitle': 'We help international companies enter, expand and grow in Brazil and across Latin America through regulatory expertise, local ecosystem intelligence and high-impact business development strategies.',
    'hero.cta1': 'Book a strategic call',
    'hero.cta2': 'Download capabilities deck',
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.news': 'News & Events',
    'nav.values': 'Values',
    'nav.ceo': 'CEO',
    'nav.contact': 'Contact',
    'about.title': 'About Melow Connect',
    'about.intro': 'Melow Connect is a strategic consultancy specialised in Market Entry, Business Development and Regulatory Navigation for healthcare, pharmaceutical and life-science companies expanding into Brazil and Latin America.',
    'about.approach.title': 'Our approach integrates',
    'about.approach.item1.title': 'Market Entry Strategy',
    'about.approach.item1.desc': 'End-to-end support for companies entering Brazil and LATAM, from opportunity mapping to regulatory pathways, ANVISA strategy and local partnerships.',
    'about.approach.item2.title': 'Business Development & Growth Acceleration',
    'about.approach.item2.desc': 'Development of commercial models, licensing opportunities, distribution networks, CMO/CDMO evaluations and strategic partnerships.',
    'about.approach.item3.title': 'Regulatory & Quality Navigation',
    'about.approach.item3.desc': 'Guidance on ANVISA pathways, product classification, regulatory intelligence, dossier strategy, and compliance frameworks.',
    'about.approach.item4.title': 'Data, Insights & Competitive Intelligence',
    'about.approach.item4.desc': 'Market sizing, pricing analyses, competitive landscapes, portfolio prioritisation and decision-driving analytics.',
    'about.purpose.title': 'Our Purpose',
    'about.purpose.desc': 'We bridge global innovation with the Brazilian market, reducing uncertainty and empowering companies to thrive in one of the most complex and promising healthcare regions in the world.',
    'services.title': 'Our Services',
    'services.subtitle': 'Comprehensive solutions structured in 4 strategic pillars',
    'services.pillar1.title': '1. Market Entry Strategy',
    'services.pillar1.item1': 'Opportunity & feasibility assessment',
    'services.pillar1.item2': 'ANVISA regulatory pathway definition',
    'services.pillar1.item3': 'Competitor & pricing intelligence',
    'services.pillar1.item4': 'Commercial model definition',
    'services.pillar1.item5': 'Partner identification & selection',
    'services.pillar2.title': '2. Business Development & Licensing',
    'services.pillar2.item1': 'In-licensing and out-licensing opportunities',
    'services.pillar2.item2': 'Distribution and co-promotion models',
    'services.pillar2.item3': 'CMO/CDMO evaluation and negotiation',
    'services.pillar2.item4': 'Portfolio expansion strategy',
    'services.pillar3.title': '3. Regulatory Affairs & Compliance (ANVISA)',
    'services.pillar3.item1': 'Dossier strategy & regulatory planning',
    'services.pillar3.item2': 'Product classification & submission support',
    'services.pillar3.item3': 'Quality & compliance advisory',
    'services.pillar3.item4': 'Lifecycle management',
    'services.pillar4.title': '4. Data & Insights',
    'services.pillar4.item1': 'Market sizing & demand modelling',
    'services.pillar4.item2': 'Pricing, reimbursement & competitive analyses',
    'services.pillar4.item3': 'Commercial performance dashboards',
    'services.pillar4.item4': 'Strategic reports for decision-making',
    'whyChooseUs.title': 'Why Work With Melow Connect',
    'whyChooseUs.subtitle': 'Personalized solutions based on deep local expertise',
    'whyChooseUs.reason1': 'Tailored solutions based on deep local expertise',
    'whyChooseUs.reason2': 'Strong network across the Brazilian healthcare ecosystem',
    'whyChooseUs.reason3': 'Proven track record with global companies',
    'whyChooseUs.reason4': 'Strategic vision with technical and regulatory accuracy',
    'whyChooseUs.reason5': 'Full support from entry to commercialisation',
    'whyBrazil.title': 'Why Brazil / Why LATAM',
    'whyBrazil.subtitle': 'Quick insights demonstrating market opportunity',
    'whyBrazil.highlight1': 'Latin America\'s largest and most dynamic healthcare market with over 215 million people',
    'whyBrazil.highlight2': 'Growing pharmaceutical market valued at $30+ billion USD with strong demand for innovation',
    'whyBrazil.highlight3': 'Gateway to Latin American expansion with established regulatory pathways',
    'whyBrazil.highlight4': 'Strong public-private healthcare system creating diverse commercial opportunities',
    'news.title': 'News & Events',
    'news.subtitle': 'Stay updated with the latest insights, articles, events and market intelligence',
    'news.linkedin.title': 'LinkedIn Posts',
    'news.linkedin.desc': 'Follow our latest insights, updates and thought leadership',
    'news.anvisa.title': 'ANVISA Updates',
    'news.anvisa.desc': 'Regulatory changes, new norms and key resolutions',
    'news.events.title': 'Events & Conferences',
    'news.events.desc': 'FCE Pharma, CPHI, EuroPLX and other key industry events',
    'news.articles.title': 'Articles & Quick Reads',
    'news.articles.desc': 'Short-form content 3-5 lines on market insights',
    'news.publications.title': 'Melow Connect Publications',
    'news.publications.desc': 'LinkedIn articles and official company publications',
    'news.interviews.title': 'Interviews & Features',
    'news.interviews.desc': 'Interviews and spotlight features with industry leaders',
    'news.comingSoon': 'Content coming soon - follow us on LinkedIn and Instagram',
    'values.purpose': 'Our Purpose',
    'values.purposeDesc': 'Connecting strategies, people and technology to transform challenges into real growth.',
    'values.quality': 'Quality',
    'values.qualityDesc': 'We translate analysis into precision and assertive decisions.',
    'values.innovation': 'Innovation',
    'values.innovationDesc': 'We combine human intelligence and AI to create solutions that generate impact.',
    'values.excellence': 'Excellence',
    'values.excellenceDesc': 'Every project is guided by ethics, consistency and long-term vision.',
    'values.partnerships': 'Partnerships',
    'values.partnershipsDesc': 'We transform relationships into lasting connections and sustainable results. Win-win approach.',
    'mission.title': 'Mission',
    'mission.description': 'To guide global companies in creating and executing market entry, expansion and brand consolidation strategies, integrating market intelligence, AI and business development — generating value, qualified pipeline and long-term strategic partnerships.',
    'vision.title': 'Vision',
    'vision.description': 'To be a reference in Latin America for strategic consulting that connects data, people and global ecosystems — driving sustainable growth and innovation in health and wellness.',
    'pillars.title': 'The pillars that sustain us',
    'pillars.partnerships': 'Strategic Partnerships',
    'pillars.innovation': 'Innovation',
    'pillars.development': 'Development',
    'legacy.title': 'Our Legacy',
    'legacy.description': 'Building sustainable partnerships and fostering innovation across the healthcare industry.',
    'legacy.partnerships': 'Strategic Partnerships',
    'legacy.innovation': 'Innovation',
    'legacy.development': 'Development',
    'legacy.quote': '"We connect innovation and strategy to transform opportunities into concrete and sustainable results."',
    'ceo.title': 'About the Founder',
    'ceo.name': 'Érica Mélo',
    'ceo.position': 'CEO & Founder',
    'ceo.bio1': 'Érica Mélo is a senior pharmaceutical executive and business development specialist with more than 24 years of experience leading market expansion, licensing, regulatory strategy and commercial operations across Latin America and Europe.',
    'ceo.bio2': 'She has worked with global organisations such as Unither Pharmaceuticals, Allergan, GSK/Stiefel, Dr. Reddy\'s, Hypera Pharma and others, building high-impact partnerships and driving the launch and growth of ophthalmic, sterile liquid, dermatology, OTC and medical-device portfolios, as well as oncology and others.',
    'ceo.bio3': 'Érica founded Melow Connect to help international healthcare companies navigate the complexity of the Brazilian market with clarity, strategy and trusted local expertise.',
    'ceo.bio4': 'Her deep understanding of ANVISA requirements, market dynamics, and local partnerships enables companies to accelerate their entry and growth in Brazil and across Latin America.',
    'contact.title': 'Let\'s talk?',
    'contact.subtitle': 'Get in touch to discover how we can help your company',
    'contact.email': 'Send email',
    'contact.call': 'Call',
    'contact.linkedin': 'Connect on LinkedIn',
    'whatsapp.message': 'Hello! I would like to speak with a Melow Connect specialist!',
    'whatsapp.button': 'Start conversation!',
    'footer.partners': 'Our Clients & Partners',
    'footer.rights': 'All rights reserved.',
  },
  'pt-BR': {
    'hero.title': 'Estratégia de Entrada no Mercado e Desenvolvimento de Negócios para Healthcare e Life Sciences no Brasil e América Latina',
    'hero.subtitle': 'Ajudamos empresas internacionais a entrar, expandir e crescer no Brasil e na América Latina através de expertise regulatória, inteligência do ecossistema local e estratégias de alto impacto.',
    'hero.cta1': 'Agendar conversa',
    'hero.cta2': 'Baixar apresentação',
    'nav.home': 'Início',
    'nav.about': 'Sobre',
    'nav.services': 'Serviços',
    'nav.news': 'News & Events',
    'nav.values': 'Valores',
    'nav.ceo': 'CEO',
    'nav.contact': 'Contato',
    'about.title': 'Sobre a Melow Connect',
    'about.intro': 'A Melow Connect é uma consultoria estratégica especializada em Entrada no Mercado, Desenvolvimento de Negócios e Navegação Regulatória para empresas de healthcare expandindo para o Brasil e América Latina.',
    'about.approach.title': 'Nossa abordagem integra',
    'about.approach.item1.title': 'Estratégia de Entrada no Mercado',
    'about.approach.item1.desc': 'Suporte completo desde mapeamento de oportunidades até caminhos regulatórios ANVISA e parcerias locais.',
    'about.approach.item2.title': 'Desenvolvimento de Negócios',
    'about.approach.item2.desc': 'Modelos comerciais, licenciamento, redes de distribuição e parcerias estratégicas.',
    'about.approach.item3.title': 'Navegação Regulatória',
    'about.approach.item3.desc': 'Orientação ANVISA, classificação de produtos e estratégia de dossiê.',
    'about.approach.item4.title': 'Dados e Insights',
    'about.approach.item4.desc': 'Análises de mercado, preços, cenários competitivos e analytics.',
    'about.purpose.title': 'Nosso Propósito',
    'about.purpose.desc': 'Conectamos inovação global com o mercado brasileiro, reduzindo incertezas e capacitando empresas a prosperar.',
    'services.title': 'Nossos Serviços',
    'services.subtitle': 'Soluções estruturadas em 4 pilares estratégicos',
    'services.pillar1.title': '1. Estratégia de Entrada no Mercado',
    'services.pillar1.item1': 'Avaliação de oportunidade e viabilidade',
    'services.pillar1.item2': 'Definição de caminho regulatório ANVISA',
    'services.pillar1.item3': 'Inteligência de concorrência e preços',
    'services.pillar1.item4': 'Definição de modelo comercial',
    'services.pillar1.item5': 'Identificação e seleção de parceiros',
    'services.pillar2.title': '2. Desenvolvimento de Negócios',
    'services.pillar2.item1': 'Oportunidades de in/out-licensing',
    'services.pillar2.item2': 'Modelos de distribuição e co-promoção',
    'services.pillar2.item3': 'Avaliação CMO/CDMO',
    'services.pillar2.item4': 'Expansão de portfólio',
    'services.pillar3.title': '3. Assuntos Regulatórios (ANVISA)',
    'services.pillar3.item1': 'Estratégia de dossiê',
    'services.pillar3.item2': 'Classificação de produtos',
    'services.pillar3.item3': 'Consultoria de qualidade',
    'services.pillar3.item4': 'Gestão de ciclo de vida',
    'services.pillar4.title': '4. Dados e Insights',
    'services.pillar4.item1': 'Dimensionamento de mercado',
    'services.pillar4.item2': 'Análises de preços e competitividade',
    'services.pillar4.item3': 'Dashboards comerciais',
    'services.pillar4.item4': 'Relatórios estratégicos',
    'whyChooseUs.title': 'Por Que Trabalhar Conosco',
    'whyChooseUs.subtitle': 'Soluções personalizadas',
    'whyChooseUs.reason1': 'Expertise local profunda',
    'whyChooseUs.reason2': 'Forte rede no ecossistema brasileiro',
    'whyChooseUs.reason3': 'Histórico comprovado',
    'whyChooseUs.reason4': 'Visão estratégica e precisão regulatória',
    'whyChooseUs.reason5': 'Suporte completo',
    'whyBrazil.title': 'Por Que Brasil / LATAM',
    'whyBrazil.subtitle': 'Oportunidade de mercado',
    'whyBrazil.highlight1': 'Maior mercado de healthcare da América Latina com 215+ milhões',
    'whyBrazil.highlight2': 'Mercado farmacêutico de $30+ bilhões USD',
    'whyBrazil.highlight3': 'Porta de entrada para LATAM',
    'whyBrazil.highlight4': 'Sistema de saúde público-privado robusto',
    'news.title': 'News & Events',
    'news.subtitle': 'Insights, artigos e inteligência de mercado',
    'news.linkedin.title': 'Posts LinkedIn',
    'news.linkedin.desc': 'Acompanhe nossos insights',
    'news.anvisa.title': 'Atualizações ANVISA',
    'news.anvisa.desc': 'Mudanças regulatórias',
    'news.events.title': 'Eventos',
    'news.events.desc': 'FCE Pharma, CPHI, EuroPLX',
    'news.articles.title': 'Artigos',
    'news.articles.desc': 'Leituras rápidas',
    'news.publications.title': 'Publicações',
    'news.publications.desc': 'Artigos oficiais',
    'news.interviews.title': 'Entrevistas',
    'news.interviews.desc': 'Destaques do setor',
    'news.comingSoon': 'Em breve - siga-nos',
    'values.purpose': 'Propósito',
    'values.purposeDesc': 'Conectar estratégias e tecnologia',
    'values.quality': 'Qualidade',
    'values.qualityDesc': 'Precisão e decisões assertivas',
    'values.innovation': 'Inovação',
    'values.innovationDesc': 'IA e inteligência humana',
    'values.excellence': 'Excelência',
    'values.excellenceDesc': 'Ética e visão de longo prazo',
    'values.partnerships': 'Parcerias',
    'values.partnershipsDesc': 'Conexões duradouras',
    'mission.title': 'Missão',
    'mission.description': 'Guiar empresas globais em estratégias de entrada e expansão no mercado brasileiro.',
    'vision.title': 'Visão',
    'vision.description': 'Ser referência em consultoria estratégica na América Latina.',
    'pillars.title': 'Nossos pilares',
    'pillars.partnerships': 'Parcerias Estratégicas',
    'pillars.innovation': 'Inovação',
    'pillars.development': 'Desenvolvimento',
    'legacy.title': 'Nosso Legado',
    'legacy.description': 'Construindo parcerias sustentáveis e fomentando inovação no setor de saúde.',
    'legacy.partnerships': 'Parcerias Estratégicas',
    'legacy.innovation': 'Inovação',
    'legacy.development': 'Desenvolvimento',
    'legacy.quote': '"Conectamos inovação e estratégia para transformar oportunidades em resultados concretos e sustentáveis."',
    'ceo.title': 'Fundadora',
    'ceo.name': 'Érica Mélo',
    'ceo.position': 'CEO & Fundadora',
    'ceo.bio1': 'Executiva farmacêutica com 24+ anos de experiência em expansão de mercado na América Latina e Europa.',
    'ceo.bio2': 'Trabalhou com Unither, Allergan, GSK, Dr. Reddy\'s, Hypera Pharma construindo parcerias de alto impacto.',
    'ceo.bio3': 'Fundou a Melow Connect para ajudar empresas internacionais no mercado brasileiro.',
    'ceo.bio4': 'Seu profundo conhecimento dos requisitos da ANVISA, dinâmica de mercado e parcerias locais permite que empresas acelerem sua entrada e crescimento no Brasil e América Latina.',
    'contact.title': 'Vamos conversar?',
    'contact.subtitle': 'Entre em contato',
    'contact.email': 'E-mail',
    'contact.call': 'Ligar',
    'contact.linkedin': 'LinkedIn',
    'whatsapp.message': 'Olá! Gostaria de falar com um especialista da Melow Connect!',
    'whatsapp.button': 'Quero falar!',
    'footer.partners': 'Nossos clientes e Parceiros',
    'footer.rights': 'Todos os direitos reservados.',
  },
  'es': {
    'hero.title': 'Estrategia de Entrada al Mercado para Healthcare en Brasil y LATAM',
    'hero.subtitle': 'Ayudamos a empresas internacionales a entrar y crecer en Brasil y América Latina.',
    'hero.cta1': 'Agendar llamada',
    'hero.cta2': 'Descargar presentación',
    'nav.home': 'Inicio',
    'nav.about': 'Acerca de',
    'nav.services': 'Servicios',
    'nav.news': 'News & Events',
    'nav.values': 'Valores',
    'nav.ceo': 'CEO',
    'nav.contact': 'Contacto',
    'about.title': 'Acerca de Melow Connect',
    'about.intro': 'Consultoría estratégica especializada en Entrada al Mercado y Desarrollo de Negocios.',
    'about.approach.title': 'Nuestro enfoque',
    'about.approach.item1.title': 'Entrada al Mercado',
    'about.approach.item1.desc': 'Soporte completo para empresas.',
    'about.approach.item2.title': 'Desarrollo de Negocios',
    'about.approach.item2.desc': 'Modelos comerciales y asociaciones.',
    'about.approach.item3.title': 'Navegación Regulatoria',
    'about.approach.item3.desc': 'Orientación ANVISA.',
    'about.approach.item4.title': 'Datos e Insights',
    'about.approach.item4.desc': 'Análisis de mercado.',
    'about.purpose.title': 'Propósito',
    'about.purpose.desc': 'Conectamos innovación global con Brasil.',
    'services.title': 'Servicios',
    'services.subtitle': '4 pilares estratégicos',
    'services.pillar1.title': '1. Entrada al Mercado',
    'services.pillar1.item1': 'Evaluación',
    'services.pillar1.item2': 'Camino ANVISA',
    'services.pillar1.item3': 'Inteligencia',
    'services.pillar1.item4': 'Modelo comercial',
    'services.pillar1.item5': 'Selección de socios',
    'services.pillar2.title': '2. Desarrollo',
    'services.pillar2.item1': 'Licenciamiento',
    'services.pillar2.item2': 'Distribución',
    'services.pillar2.item3': 'CMO/CDMO',
    'services.pillar2.item4': 'Expansión',
    'services.pillar3.title': '3. Regulatorio',
    'services.pillar3.item1': 'Estrategia',
    'services.pillar3.item2': 'Clasificación',
    'services.pillar3.item3': 'Calidad',
    'services.pillar3.item4': 'Ciclo de vida',
    'services.pillar4.title': '4. Datos',
    'services.pillar4.item1': 'Mercado',
    'services.pillar4.item2': 'Precios',
    'services.pillar4.item3': 'Dashboards',
    'services.pillar4.item4': 'Informes',
    'whyChooseUs.title': 'Por Qué Elegirnos',
    'whyChooseUs.subtitle': 'Soluciones personalizadas',
    'whyChooseUs.reason1': 'Experiencia local',
    'whyChooseUs.reason2': 'Red fuerte',
    'whyChooseUs.reason3': 'Historial probado',
    'whyChooseUs.reason4': 'Visión estratégica',
    'whyChooseUs.reason5': 'Soporte completo',
    'whyBrazil.title': 'Por Qué Brasil',
    'whyBrazil.subtitle': 'Oportunidad',
    'whyBrazil.highlight1': 'Mayor mercado LATAM',
    'whyBrazil.highlight2': 'Mercado $30B+',
    'whyBrazil.highlight3': 'Puerta LATAM',
    'whyBrazil.highlight4': 'Sistema robusto',
    'news.title': 'News & Events',
    'news.subtitle': 'Actualizaciones',
    'news.linkedin.title': 'LinkedIn',
    'news.linkedin.desc': 'Insights',
    'news.anvisa.title': 'ANVISA',
    'news.anvisa.desc': 'Cambios',
    'news.events.title': 'Eventos',
    'news.events.desc': 'Conferencias',
    'news.articles.title': 'Artículos',
    'news.articles.desc': 'Lecturas',
    'news.publications.title': 'Publicaciones',
    'news.publications.desc': 'Oficiales',
    'news.interviews.title': 'Entrevistas',
    'news.interviews.desc': 'Destacados',
    'news.comingSoon': 'Próximamente',
    'values.purpose': 'Propósito',
    'values.purposeDesc': 'Conectar estrategias',
    'values.quality': 'Calidad',
    'values.qualityDesc': 'Precisión',
    'values.innovation': 'Innovación',
    'values.innovationDesc': 'IA e inteligencia',
    'values.excellence': 'Excelencia',
    'values.excellenceDesc': 'Ética',
    'values.partnerships': 'Asociaciones',
    'values.partnershipsDesc': 'Conexiones',
    'mission.title': 'Misión',
    'mission.description': 'Guiar empresas globales.',
    'vision.title': 'Visión',
    'vision.description': 'Ser referencia LATAM.',
    'pillars.title': 'Nuestros pilares',
    'pillars.partnerships': 'Asociaciones Estratégicas',
    'pillars.innovation': 'Innovación',
    'pillars.development': 'Desarrollo',
    'legacy.title': 'Nuestro Legado',
    'legacy.description': 'Construyendo asociaciones sostenibles y fomentando innovación en el sector salud.',
    'legacy.partnerships': 'Asociaciones Estratégicas',
    'legacy.innovation': 'Innovación',
    'legacy.development': 'Desarrollo',
    'legacy.quote': '"Conectamos innovación y estrategia para transformar oportunidades en resultados concretos y sostenibles."',
    'ceo.title': 'Fundadora',
    'ceo.name': 'Érica Mélo',
    'ceo.position': 'CEO',
    'ceo.bio1': 'Ejecutiva farmacéutica con 24+ años de experiencia en expansión de mercado en América Latina y Europa.',
    'ceo.bio2': 'Trabajó con Unither, Allergan, GSK, Dr. Reddy\'s, Hypera Pharma construyendo asociaciones de alto impacto.',
    'ceo.bio3': 'Fundó Melow Connect para ayudar a empresas internacionales en el mercado brasileño.',
    'ceo.bio4': 'Su profundo conocimiento de los requisitos de ANVISA, dinámica del mercado y asociaciones locales permite que empresas aceleren su entrada y crecimiento en Brasil y América Latina.',
    'contact.title': '¿Hablamos?',
    'contact.subtitle': 'Contáctenos',
    'contact.email': 'Email',
    'contact.call': 'Llamar',
    'contact.linkedin': 'LinkedIn',
    'whatsapp.message': '¡Hola! ¡Me gustaría hablar con un especialista de Melow Connect!',
    'whatsapp.button': '¡Quiero hablar!',
    'footer.partners': 'Nuestros clientes y Socios',
    'footer.rights': 'Derechos reservados.',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};