import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'pt-BR' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  'pt-BR': {
    'hero.title': 'Conectando dados, estratégia e tecnologia',
    'hero.subtitle': 'Consultoria estratégica para impulsionar empresas internacionais no Brasil e América Latina',
    'hero.contact': 'Entre em contato',
    'hero.learnMore': 'Saiba mais',
    'nav.home': 'Início',
    'nav.about': 'Sobre',
    'nav.services': 'Serviços',
    'nav.values': 'Valores',
    'nav.ceo': 'CEO',
    'nav.contact': 'Contato',
    'contact.title': 'Vamos conversar?',
    'contact.subtitle': 'Entre em contato para descobrir como podemos ajudar sua empresa',
    'contact.email': 'Enviar e-mail',
    'contact.call': 'Ligar',
    'contact.linkedin': 'Conectar no LinkedIn',
    'about.title': 'Sobre a Melow Connect',
    'about.description': 'A Melow Connect é uma consultoria estratégica que conecta dados, estratégia e inovação para impulsionar a entrada e o crescimento de empresas internacionais no Brasil e na América Latina.',
    'services.title': 'Áreas de Atuação',
    'services.subtitle': 'Novos negócios, Brand Plan, Business Intelligence & IA',
    'services.newBusiness': 'Business Development',
    'services.newBusinessDesc': 'Desenvolvimento estratégico de oportunidades e expansão de mercado',
    'services.market': 'Entrada no Mercado',
    'services.marketDesc': 'Curadoria estratégica de oportunidades e parceiros, selecionando os melhores caminhos — parcerias, distribuidor/CMO, joint ventures ou entrada direta.',
    'services.brand': 'Brand Plan & Go-to-Market',
    'services.brandDesc': 'Planejamento e execução de marca com posicionamento e forecasting.',
    'services.tech': 'Soluções de Tecnologia & IA',
    'services.techDesc': 'Integração de IA e analytics para decisões de negócio.',
    'services.bi': 'Business Intelligence & Insights',
    'services.biDesc': 'Dashboards e relatórios preditivos orientados à ação, cálculo premiação da FV.',
    'services.people': 'Pessoas',
    'services.peopleDesc': 'Buscamos as pessoas certas para o seu negócio.',
    'services.governance': 'Governança e Compliance',
    'services.governanceDesc': 'Suporte jurídico e compliance.',
    'services.network': 'Network e Ecossistema',
    'services.networkDesc': 'Através da nossa curadoria e expertise de mercado, conectamos o cliente às empresas.',
    'services.regulatory': 'Apoio Regulatório e Qualidade',
    'services.regulatoryDesc': 'Identificamos sua necessidade nesse quesito e oferecemos a solução ideal para o momento e tamanho da sua empresa.',
    'values.purpose': 'Nosso Propósito',
    'values.purposeDesc': 'Conectar estratégias, pessoas e tecnologia para transformar desafios em crescimento real.',
    'values.quality': 'Qualidade',
    'values.qualityDesc': 'Traduzimos análise em precisão e decisões assertivas.',
    'values.innovation': 'Inovação',
    'values.innovationDesc': 'Combinamos inteligência humana e IA para criar soluções que geram impacto.',
    'values.excellence': 'Excelência',
    'values.excellenceDesc': 'Cada projeto é guiado por ética, consistência e visão de longo prazo.',
    'values.partnerships': 'Parcerias',
    'values.partnershipsDesc': 'Transformamos relações em conexões duradouras e resultados sustentáveis. Abordagem ganha-ganha.',
    'mission.title': 'Missão',
    'mission.description': 'Guiar empresas globais na criação e execução de estratégias de entrada, expansão e consolidação de marca, integrando inteligência de mercado, IA e business development — gerando valor, pipeline qualificado e parcerias estratégicas de longo prazo.',
    'vision.title': 'Visão',
    'vision.description': 'Ser referência na América Latina em consultoria estratégica que conecta dados, pessoas e ecossistemas globais — impulsionando crescimento sustentável e inovação em saúde e bem-estar.',
    'pillars.title': 'Os pilares que nos sustentam',
    'pillars.global': 'Conexões Globais e Locais',
    'pillars.globalDesc': 'Unimos o conhecimento internacional à sensibilidade local.',
    'pillars.intelligence': 'Inteligência Estratégica Integrada',
    'pillars.intelligenceDesc': 'Transformamos dados e insights em vantagem competitiva.',
    'pillars.execution': 'Execução com Propósito e Excelência',
    'pillars.executionDesc': 'Da estratégia à ação, entregamos impacto real.',
    'legacy.title': 'Nosso Legado para o Mundo',
    'legacy.description': 'Na Melow Connect, acreditamos que o verdadeiro sucesso é construído por meio de conexões significativas. Nosso legado é transformar conhecimento em impacto, tecnologia em propósito e parcerias em prosperidade compartilhada.',
    'legacy.partnerships': 'Parcerias Ganha-Ganha',
    'legacy.innovation': 'Inovação com Propósito',
    'legacy.development': 'Desenvolvimento de Pessoas e Conhecimento',
    'legacy.quote': 'Nosso legado é construir pontes que transformam negócios e pessoas em histórias de sucesso.',
    'ceo.title': 'CEO & Fundadora',
    'ceo.position': 'CEO & Fundadora',
    'ceo.bio1': 'Érica Mélo é uma executiva com mais de 25 anos de experiência em desenvolvimento de negócios, excelência comercial e estratégia internacional, atuando em empresas como Unither Pharmaceuticals, Allergan (AbbVie), GlaxoSmithKline, Dr. Reddys e Hypera Pharma.',
    'ceo.bio2': 'Possui trajetória consolidada na América Latina e Europa, liderando projetos de Business Development, M&A, licenciamento e entrada de produtos em novos mercados.',
    'ceo.bio3': 'MBA em Inteligência Artificial, Ciência de Dados e Big Data para Negócios. Reconhecida por formar equipes de alta performance e implementar estruturas de governança robustas.',
    'ceo.bio4': 'Atualmente, lidera a Melow Connect, apoiando empresas internacionais na definição de estratégias de entrada e crescimento no mercado latino-americano.',
    'footer.rights': 'Todos os direitos reservados.',
    'footer.partners': 'Nossos Parceiros',
  },
  'en': {
    'hero.title': 'Connecting data, strategy and technology',
    'hero.subtitle': 'Strategic consulting to drive international companies in Brazil and Latin America',
    'hero.contact': 'Get in touch',
    'hero.learnMore': 'Learn more',
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.values': 'Values',
    'nav.ceo': 'CEO',
    'nav.contact': 'Contact',
    'contact.title': 'Let\'s talk?',
    'contact.subtitle': 'Contact us to discover how we can help your company',
    'contact.email': 'Send email',
    'contact.call': 'Call',
    'contact.linkedin': 'Connect on LinkedIn',
    'about.title': 'About Melow Connect',
    'about.description': 'Melow Connect is a strategic consulting firm that connects data, strategy and innovation to drive the entry and growth of international companies in Brazil and Latin America.',
    'services.title': 'Areas of Expertise',
    'services.subtitle': 'New Business, Brand Plan, Business Intelligence & AI',
    'services.newBusiness': 'Business Development',
    'services.newBusinessDesc': 'Strategic development of opportunities and market expansion',
    'services.market': 'Market Entry',
    'services.marketDesc': 'Strategic curation of opportunities and partners, selecting the best paths — partnerships, distributor/CMO, joint ventures or direct entry.',
    'services.brand': 'Brand Plan & Go-to-Market',
    'services.brandDesc': 'Brand planning and execution with positioning and forecasting.',
    'services.tech': 'Technology & AI Solutions',
    'services.techDesc': 'AI and analytics integration for business decisions.',
    'services.bi': 'Business Intelligence & Insights',
    'services.biDesc': 'Action-oriented predictive dashboards and reports, sales force incentive calculation.',
    'services.people': 'People',
    'services.peopleDesc': 'We find the right people for your business.',
    'services.governance': 'Governance and Compliance',
    'services.governanceDesc': 'Legal support and compliance.',
    'services.network': 'Network and Ecosystem',
    'services.networkDesc': 'Through our curation and market expertise, we connect clients to companies.',
    'services.regulatory': 'Regulatory and Quality Support',
    'services.regulatoryDesc': 'We identify your needs in this area and offer the ideal solution for your company\'s moment and size.',
    'values.purpose': 'Our Purpose',
    'values.purposeDesc': 'Connect strategies, people and technology to transform challenges into real growth.',
    'values.quality': 'Quality',
    'values.qualityDesc': 'We translate analysis into precision and assertive decisions.',
    'values.innovation': 'Innovation',
    'values.innovationDesc': 'We combine human intelligence and AI to create solutions that generate impact.',
    'values.excellence': 'Excellence',
    'values.excellenceDesc': 'Each project is guided by ethics, consistency and long-term vision.',
    'values.partnerships': 'Partnerships',
    'values.partnershipsDesc': 'We transform relationships into lasting connections and sustainable results. Win-win approach.',
    'mission.title': 'Mission',
    'mission.description': 'Guide global companies in creating and executing market entry, expansion and brand consolidation strategies, integrating market intelligence, AI and business development — generating value, qualified pipeline and long-term strategic partnerships.',
    'vision.title': 'Vision',
    'vision.description': 'Be a reference in Latin America in strategic consulting that connects data, people and global ecosystems — driving sustainable growth and innovation in health and wellness.',
    'pillars.title': 'The pillars that sustain us',
    'pillars.global': 'Global and Local Connections',
    'pillars.globalDesc': 'We unite international knowledge with local sensitivity.',
    'pillars.intelligence': 'Integrated Strategic Intelligence',
    'pillars.intelligenceDesc': 'We transform data and insights into competitive advantage.',
    'pillars.execution': 'Execution with Purpose and Excellence',
    'pillars.executionDesc': 'From strategy to action, we deliver real impact.',
    'legacy.title': 'Our Legacy to the World',
    'legacy.description': 'At Melow Connect, we believe true success is built through meaningful connections. Our legacy is to transform knowledge into impact, technology into purpose and partnerships into shared prosperity.',
    'legacy.partnerships': 'Win-Win Partnerships',
    'legacy.innovation': 'Innovation with Purpose',
    'legacy.development': 'People and Knowledge Development',
    'legacy.quote': 'Our legacy is to build bridges that transform businesses and people into success stories.',
    'ceo.title': 'CEO & Founder',
    'ceo.position': 'CEO & Founder',
    'ceo.bio1': 'Érica Mélo is an executive with over 25 years of experience in business development, commercial excellence and international strategy, working at companies such as Unither Pharmaceuticals, Allergan (AbbVie), GlaxoSmithKline, Dr. Reddys and Hypera Pharma.',
    'ceo.bio2': 'She has a consolidated track record in Latin America and Europe, leading Business Development, M&A, licensing and market entry projects.',
    'ceo.bio3': 'MBA in Artificial Intelligence, Data Science and Big Data for Business. Recognized for building high-performance teams and implementing robust governance structures.',
    'ceo.bio4': 'Currently leads Melow Connect, supporting international companies in defining entry and growth strategies in the Latin American market.',
    'footer.rights': 'All rights reserved.',
    'footer.partners': 'Our Partners',
  },
  'es': {
    'hero.title': 'Conectando datos, estrategia y tecnología',
    'hero.subtitle': 'Consultoría estratégica para impulsar empresas internacionales en Brasil y América Latina',
    'hero.contact': 'Contáctenos',
    'hero.learnMore': 'Saber más',
    'nav.home': 'Inicio',
    'nav.about': 'Acerca de',
    'nav.services': 'Servicios',
    'nav.values': 'Valores',
    'nav.ceo': 'CEO',
    'nav.contact': 'Contacto',
    'contact.title': '¿Hablamos?',
    'contact.subtitle': 'Contáctenos para descubrir cómo podemos ayudar a su empresa',
    'contact.email': 'Enviar correo',
    'contact.call': 'Llamar',
    'contact.linkedin': 'Conectar en LinkedIn',
    'about.title': 'Acerca de Melow Connect',
    'about.description': 'Melow Connect es una consultoría estratégica que conecta datos, estrategia e innovación para impulsar la entrada y el crecimiento de empresas internacionales en Brasil y América Latina.',
    'services.title': 'Áreas de Actuación',
    'services.subtitle': 'Nuevos Negocios, Brand Plan, Business Intelligence & IA',
    'services.newBusiness': 'Business Development',
    'services.newBusinessDesc': 'Desarrollo estratégico de oportunidades y expansión de mercado',
    'services.market': 'Entrada al Mercado',
    'services.marketDesc': 'Curaduría estratégica de oportunidades y socios, seleccionando los mejores caminos — alianzas, distribuidor/CMO, joint ventures o entrada directa.',
    'services.brand': 'Brand Plan & Go-to-Market',
    'services.brandDesc': 'Planificación y ejecución de marca con posicionamiento y forecasting.',
    'services.tech': 'Soluciones de Tecnología & IA',
    'services.techDesc': 'Integración de IA y analytics para decisiones de negocio.',
    'services.bi': 'Business Intelligence & Insights',
    'services.biDesc': 'Dashboards e informes predictivos orientados a la acción, cálculo de remuneración de FV.',
    'services.people': 'Personas',
    'services.peopleDesc': 'Buscamos las personas adecuadas para su negocio.',
    'services.governance': 'Gobernanza y Compliance',
    'services.governanceDesc': 'Soporte jurídico y compliance.',
    'services.network': 'Network y Ecosistema',
    'services.networkDesc': 'A través de nuestra curaduría y experiencia de mercado, conectamos al cliente con las empresas.',
    'services.regulatory': 'Apoyo Regulatorio y Calidad',
    'services.regulatoryDesc': 'Identificamos su necesidad en este aspecto y ofrecemos la solución ideal para el momento y tamaño de su empresa.',
    'values.purpose': 'Nuestro Propósito',
    'values.purposeDesc': 'Conectar estrategias, personas y tecnología para transformar desafíos en crecimiento real.',
    'values.quality': 'Calidad',
    'values.qualityDesc': 'Traducimos análisis en precisión y decisiones asertivas.',
    'values.innovation': 'Innovación',
    'values.innovationDesc': 'Combinamos inteligencia humana e IA para crear soluciones que generan impacto.',
    'values.excellence': 'Excelencia',
    'values.excellenceDesc': 'Cada proyecto es guiado por ética, consistencia y visión a largo plazo.',
    'values.partnerships': 'Alianzas',
    'values.partnershipsDesc': 'Transformamos relaciones en conexiones duraderas y resultados sostenibles. Enfoque ganar-ganar.',
    'mission.title': 'Misión',
    'mission.description': 'Guiar empresas globales en la creación y ejecución de estrategias de entrada, expansión y consolidación de marca, integrando inteligencia de mercado, IA y business development — generando valor, pipeline calificado y alianzas estratégicas a largo plazo.',
    'vision.title': 'Visión',
    'vision.description': 'Ser referencia en América Latina en consultoría estratégica que conecta datos, personas y ecosistemas globales — impulsando crecimiento sostenible e innovación en salud y bienestar.',
    'pillars.title': 'Los pilares que nos sostienen',
    'pillars.global': 'Conexiones Globales y Locales',
    'pillars.globalDesc': 'Unimos el conocimiento internacional con la sensibilidad local.',
    'pillars.intelligence': 'Inteligencia Estratégica Integrada',
    'pillars.intelligenceDesc': 'Transformamos datos e insights en ventaja competitiva.',
    'pillars.execution': 'Ejecución con Propósito y Excelencia',
    'pillars.executionDesc': 'De la estrategia a la acción, entregamos impacto real.',
    'legacy.title': 'Nuestro Legado para el Mundo',
    'legacy.description': 'En Melow Connect, creemos que el verdadero éxito se construye a través de conexiones significativas. Nuestro legado es transformar conocimiento en impacto, tecnología en propósito y alianzas en prosperidad compartida.',
    'legacy.partnerships': 'Alianzas Ganar-Ganar',
    'legacy.innovation': 'Innovación con Propósito',
    'legacy.development': 'Desarrollo de Personas y Conocimiento',
    'legacy.quote': 'Nuestro legado es construir puentes que transforman negocios y personas en historias de éxito.',
    'ceo.title': 'CEO & Fundadora',
    'ceo.position': 'CEO & Fundadora',
    'ceo.bio1': 'Érica Mélo es una ejecutiva con más de 25 años de experiencia en desarrollo de negocios, excelencia comercial y estrategia internacional, actuando en empresas como Unither Pharmaceuticals, Allergan (AbbVie), GlaxoSmithKline, Dr. Reddys e Hypera Pharma.',
    'ceo.bio2': 'Posee trayectoria consolidada en América Latina y Europa, liderando proyectos de Business Development, M&A, licenciamiento y entrada de productos en nuevos mercados.',
    'ceo.bio3': 'MBA en Inteligencia Artificial, Ciencia de Datos y Big Data para Negocios. Reconocida por formar equipos de alto desempeño e implementar estructuras de gobernanza robustas.',
    'ceo.bio4': 'Actualmente, lidera Melow Connect, apoyando empresas internacionales en la definición de estrategias de entrada y crecimiento en el mercado latinoamericano.',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.partners': 'Nuestros Socios',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'pt-BR';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
